if (LIBEVENT1_INCLUDE_DIR AND LIBEVENT1_LIBRARY)
  set (LIBEVENT1_FOUND TRUE)
else (LIBEVENT1_INCLUDE_DIR AND LIBEVENT1_LIBRARY)
  find_path (LIBEVENT1_INCLUDE_DIR event.h )
  find_library (LIBEVENT1_LIBRARY)

  include(FindPackageHandleStandardArgs)

  find_package_handle_standard_args(LibEvent1 REQUIRED_VARS LIBEVENT1_INCLUDE_DIR LIBEVENT1_LIBRARY)
endif (LIBEVENT1_INCLUDE_DIR AND LIBEVENT1_LIBRARY)
