if (LIBEVENT2_INCLUDE_DIR AND LIBEVENT2_LIBRARY)
  set (LIBEVENT2_FOUND TRUE)
else (LIBEVENT2_INCLUDE_DIR AND LIBEVENT2_LIBRARY)
  find_path (LIBEVENT2_INCLUDE_DIR event2/event.h HINTS /usr/include/event2 )
  find_library (LIBEVENT2_LIBRARY NAMES event)

  include(FindPackageHandleStandardArgs)

  find_package_handle_standard_args(LibEvent2 REQUIRED_VARS LIBEVENT2_INCLUDE_DIR LIBEVENT2_LIBRARY)
endif (LIBEVENT2_INCLUDE_DIR AND LIBEVENT2_LIBRARY)
